### ISSUE TITLE
How to infer private videos？

### ISSUE THREAD

**Issue by jiyuwangbupt** [xing0047/TPS#15]

**Comment by xing0047** [comment]
Hi,

Would you like to share more details over this problem so that I can help? Thanks.

**Comment by jiyuwangbupt** [comment]
> Hi,
> 
> Would you like to share more details over this problem so that I can help? Thanks.

Because I see that your repository only contains training and testing code, how should I perform inference on a single video (my own private video data)?

**Comment by xing0047** [comment]
Hi,

Thank you for your feedback. One suggestion is to include video loader, model loader and model inference in one file, with `video_path` as input.

For video loader, you may refer to [\_\_getitem\_\_](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/dataset/CityscapesSeq.py#L38). A video is pre-saved as frames here. Please make sure that video frames go through the same [preprocess](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/dataset/CityscapesSeq.py#L50). Dataloader is no longer needed for your use case.

For model loader, please refer [here](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/scripts/test.py#L53), where model is prepared for inference.

For model inference, please refer to [this code](https://github.com/xing0047/TPS/blob/main/tps/domain_adaptation/eval_video_UDA.py). You may check function [eval_video_demo](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/domain_adaptation/eval_video_UDA.py#L43) for further details.

**Comment by jiyuwangbupt** [comment]
> Hi,
> 
> Thank you for your feedback. One suggestion is to include video loader, model loader and model inference in one file, with `video_path` as input.
> 
> For video loader, you may refer to [__getitem__](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/dataset/CityscapesSeq.py#L38). A video is pre-saved as frames here. Please make sure that video frames go through the same [preprocess](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/dataset/CityscapesSeq.py#L50). Dataloader is no longer needed for your use case.
> 
> For model loader, please refer [here](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/scripts/test.py#L53), where model is prepared for inference.
> 
> For model inference, please refer to [this code](https://github.com/xing0047/TPS/blob/main/tps/domain_adaptation/eval_video_UDA.py). You may check function [eval_video_demo](https://github.com/xing0047/TPS/blob/12e09b4e64c6073aea8418d6447dd80c0761fdbd/tps/domain_adaptation/eval_video_UDA.py#L43) for further details.

Thank you very much. I modified the code for inference (generating optical flow images by running the optical flow algorithm separately), but there is a bug issue due to PyTorch version incompatibility。

This line of code pred_main = models[0](image.cuda(device), image2.cuda(device), flow, device)[1] throws an error: RuntimeError: CUDA error: no kernel image is available for execution on the device. My CUDA version is relatively high at 11.7, and I learned that PyTorch version 1.2.0 only supports CUDA versions 9.2 and 10.0. However, those two CUDA versions only support Ubuntu 18.04, while my system is Ubuntu 22.04. When I tried to install a version of PyTorch that matches CUDA 11.7, running the command python ./TPS/tps/utils/resample2d_package/setup.py build also threw an error (C++ compilation failed). I would like to know if there are any better solutions available.

**Comment by jiyuwangbupt** [comment]
(TPS2) jyw@rtx6000:~/TPS/tps/utils/resample2d_package$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
(TPS2) jyw@rtx6000:~/TPS/tps/utils/resample2d_package$ nvidia-smi
Thu Nov  7 11:42:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX 6000 Ada Gene...    Off | 00000000:01:00.0 Off |                    0 |
| 30%   39C    P8              27W / 300W |    199MiB / 46068MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   2568870      G   /usr/lib/xorg/Xorg                           89MiB |
|    0   N/A  N/A   2569059      G   /usr/bin/gnome-shell                         52MiB |
|    0   N/A  N/A   2569569      G   /usr/libexec/gnome-initial-setup             43MiB |
+---------------------------------------------------------------------------------------+
(TPS2) jyw@rtx6000:~/TPS/tps/utils/resample2d_package$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

**Comment by xing0047** [comment]
Hi @jiyuwangbupt 

I see the problem here. Can you try using a higher torch version to match cuda and nvcc? Will this issue persist?

**Comment by jiyuwangbupt** [comment]
> Hi @jiyuwangbupt
> 
> I see the problem here. Can you try using a higher torch version to match cuda and nvcc? Will this issue persist?

I use this command in python 3.8 (python3.6 not support cuda11.7,torch 1.13.0)：
pip install torch==1.13.0+cu117 torchvision==0.14.0+cu117 torchaudio==0.13.0 --extra-index-url https://download.pytorch.org/whl/cu117。
but, command "python ./TPS/tps/utils/resample2d_package/setup.py build" return error:
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/dist.py", line 950, in run_command
    super().run_command(command)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/jyw/anaconda3/envs/TPS2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
![image](https://github.com/user-attachments/assets/0bce15ce-a130-4b95-9502-dab15a7a268d)

**Comment by jiyuwangbupt** [comment]
[output.log](https://github.com/user-attachments/files/17656913/output.log)
This is log

**Comment by xing0047** [comment]
Hi @jiyuwangbupt 

Can you check if this may help you? (https://github.com/NVIDIA/flownet2-pytorch/issues/227)

**Comment by jiyuwangbupt** [comment]
> Hi @jiyuwangbupt
> 
> Can you check if this may help you? ([NVIDIA/flownet2-pytorch#227](https://github.com/NVIDIA/flownet2-pytorch/issues/227))

翻译成英文：非常感谢，环境跑通了，但是最后可视化保存的结果是灰白色的。我修改了test.py，CityscapesSeq.py，base_dataset.py，config.py, eval_video_demo函数。


**test.py**：
import argparse
import os
import os.path as osp
import pprint
import warnings
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from torch.utils import data

from tps.model.accel_deeplabv2 import get_accel_deeplab_v2
from tps.dataset.CityscapesSeq import CityscapesSeqDataSet
from tps.domain_adaptation.eval_video_UDA import evaluate_domain_adaptation
from tps.domain_adaptation.config import cfg, cfg_from_file

warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore")


def get_arguments():
    """
    Parse input arguments
    """
    parser = argparse.ArgumentParser(description="Code for evaluation")
    parser.add_argument('--cfg', type=str, default=None,
                        help='optional config file', )
    parser.add_argument("--exp-suffix", type=str, default=None,
                        help="optional experiment suffix")
    return parser.parse_args()


def main(config_file, exp_suffix):
    # LOAD ARGS
    assert config_file is not None, 'Missing cfg file'
    cfg_from_file(config_file)
    # auto-generate exp name if not specified
    if cfg.EXP_NAME == '':
        cfg.EXP_NAME = f'{cfg.SOURCE}2{cfg.TARGET}_{cfg.TRAIN.MODEL}_{cfg.TRAIN.DA_METHOD}'
    if exp_suffix:
        cfg.EXP_NAME += f'_{exp_suffix}'
    # auto-generate snapshot path if not specified
    if cfg.TEST.SNAPSHOT_DIR[0] == '':
        cfg.TEST.SNAPSHOT_DIR[0] = osp.join(cfg.EXP_ROOT_SNAPSHOT, cfg.EXP_NAME)
        os.makedirs(cfg.TEST.SNAPSHOT_DIR[0], exist_ok=True)

    print('Using config:')
    pprint.pprint(cfg)
    # load models
    models = []
    n_models = len(cfg.TEST.MODEL)
    if cfg.TEST.MODE == 'best':
        assert n_models == 1, 'Not yet supported'
    for i in range(n_models):
        if cfg.TEST.MODEL[i] == 'ACCEL_DeepLabv2':
            model = get_accel_deeplab_v2(num_classes=cfg.NUM_CLASSES,
                                   multi_level=cfg.TEST.MULTI_LEVEL[i])
        else:
            raise NotImplementedError(f"Not yet supported {cfg.TEST.MODEL[i]}")
        models.append(model)

    if os.environ.get('ADVENT_DRY_RUN', '0') == '1':
        return
    # print("数据信息",cfg.DATA_DIRECTORY_TARGET)
    # print(cfg.DATA_LIST_TARGET)
    # dataloaders
    # test_dataset = CityscapesSeqDataSet(root=cfg.DATA_DIRECTORY_TARGET,
    #                                  list_path=cfg.DATA_LIST_TARGET,
    #                                  set=cfg.TEST.SET_TARGET,
    #                                  crop_size=cfg.TEST.INPUT_SIZE_TARGET,
    #                                  mean=cfg.TEST.IMG_MEAN,
    #                                  labels_size=cfg.TEST.OUTPUT_SIZE_TARGET,
    #                                     interval=cfg.TEST.INTERVAL)
    # test_loader = data.DataLoader(test_dataset,
    #                               batch_size=cfg.TEST.BATCH_SIZE_TARGET,
    #                               num_workers=cfg.NUM_WORKERS,
    #                               shuffle=False,
    #                               pin_memory=True)
    
    test_dataset = CityscapesSeqDataSet(
        root='/home/jyw/TPS/frame',  # 图像所在的根目录
        list_path='/home/jyw/TPS/val.txt',  # 列表文件路径
        set='val',
        max_iters=None,
        crop_size=(321, 321), 
        mean=(128, 128, 128),
        interval=1
    )
    test_loader = data.DataLoader(
        test_dataset,
        batch_size=cfg.TEST.BATCH_SIZE_TARGET,
        num_workers=cfg.NUM_WORKERS,
        shuffle=False,
        pin_memory=True
    )
    # eval
    evaluate_domain_adaptation(models, test_loader, cfg)


if __name__ == '__main__':
    args = get_arguments()
    print('Called with args:')
    print(args)
    main(args.cfg, args.exp_suffix)

**CityscapesSeq.py**：
import numpy as np
import torch
from tps.dataset.base_dataset import BaseDataset

class CityscapesSeqDataSet(BaseDataset):
    def __init__(self, 
                 root, 
                 list_path, 
                 set='val',
                 max_iters=None,
                 crop_size=(321, 321), 
                 mean=(128, 128, 128),
                 interval=1):
        super().__init__(root, list_path, set, max_iters, crop_size, mean)
        self.interval = interval

    def get_metadata(self, name):
        img_file = self.root / name
        return img_file

    def __getitem__(self, index):
        img_file, name_cf = self.files[index]
        frame_cf = int(name_cf.replace('.png', ''))  # 处理图像文件名获取帧编号
        
        #当前帧
        # print("具体信息",img_file,name_cf,frame_cf)
        d = self.get_image(img_file)
        image_d = self.preprocess(d)

        # 前一帧
        name_kf = name_cf.replace(str(frame_cf).zfill(1) + '.png',
                                   str(frame_cf - 1).zfill(1) + '.png')
        # print("前一侦",name_kf)
        file_kf = self.root / name_kf
        c = self.get_image(file_kf)
        image_c = self.preprocess(c)

        # 前两帧
        name_kf = name_cf.replace(str(frame_cf).zfill(1) + '.png',
                                   str(frame_cf - self.interval).zfill(1) + '.png')
        # print("前二侦",name_kf)
        file_kf = self.root / name_kf
        b = self.get_image(file_kf)
        image_b = self.preprocess(b)

        # 前三帧
        name_kf = name_cf.replace(str(frame_cf).zfill(1) + '.png',
                                   str(frame_cf - self.interval - 1).zfill(1) + '.png')
        # print("前三侦",name_kf)
        file_kf = self.root / name_kf
        a = self.get_image(file_kf)
        image_a = self.preprocess(a)

        frames = torch.tensor([frame_cf, frame_cf - 1, frame_cf - self.interval, frame_cf - self.interval - 1])
        print("name_cf",name_cf)
        if self.set == 'train':
            return image_d.copy(), image_c.copy(), image_b.copy(), image_a.copy(), d.transpose(2, 0, 1), name_cf, frames
        else:
            return image_d.copy(), image_c.copy(), image_b.copy(), image_a.copy(), name_cf


**base_dataset.py**：
from pathlib import Path
import numpy as np
from PIL import Image
from torch.utils import data
import random
import imageio

class BaseDataset(data.Dataset):
    def __init__(self, root, list_path, set_,
                 max_iters, image_size, mean):
        self.root = Path(root)
        self.set = set_
        self.list_path = list_path.format(self.set)
        self.image_size = image_size
        self.mean = mean
        
        # 读取图像文件名称
        with open(self.list_path) as f:
            self.img_ids = [i_id.strip() for i_id in f]
        
        # 如果 max_iters 不为 None，重复文件名列表
        if max_iters is not None:
            self.img_ids = self.img_ids * int(np.ceil(float(max_iters) / len(self.img_ids)))
        
        self.files = []
        for name in self.img_ids:
            img_file = self.get_image_file(name)  # 获取图像文件路径
            self.files.append((img_file, name))
        print("单独的图像名字",self.files)

    def get_image_file(self, name):
        return self.root / name  # 返回完整图像文件路径

    def __len__(self):
        return len(self.files)

    def preprocess(self, image):
        image = image[:, :, ::-1]  # 将图像从 RGB 转为 BGR
        image -= self.mean  # 减去均值
        return image.transpose((2, 0, 1))  # 将 HWC 转为 CHW

    def get_image(self, file):
        return _load_img(file, self.image_size, Image.BICUBIC, rgb=True)

def _load_img(file, size, interpolation, rgb):
    print("_load_img函数",file)
    img = Image.open(file)
    if rgb:
        img = img.convert('RGB')
    img = img.resize(size, interpolation)
    return np.asarray(img, np.float32)


eval_video_demo function：
def eval_video_demo(cfg, models,
                device, test_loader, interp,
                fixed_test_size, verbose):
    if cfg.SOURCE == 'Viper':
        palette = [128, 64, 128, 244, 35, 232, 70, 70, 70, 190, 153, 153, 250, 170, 30,
                   220, 220, 0, 107, 142, 35, 152, 251, 152, 70, 130, 180, 220, 20, 60, 0, 0, 142, 0, 0, 70,
                   0, 60, 100, 0, 0, 230, 119, 11, 32]
    elif cfg.SOURCE == 'SynthiaSeq':
        palette = [128, 64, 128, 244, 35, 232, 70, 70, 70, 190, 153, 153, 153, 153, 153, 250, 170, 30,
                   220, 220, 0, 107, 142, 35, 70, 130, 180, 220, 20, 60, 255, 0, 0, 0, 0, 142]
    zero_pad = 256 * 3 - len(palette)
    for i in range(zero_pad):
        palette.append(0)
    def colorize_mask(mask):
        # mask: numpy array of the mask
        new_mask = Image.fromarray(mask.astype(np.uint8)).convert('P')
        new_mask.putpalette(palette)
        return new_mask
    num_classes = cfg.NUM_CLASSES
    assert len(cfg.TEST.RESTORE_FROM) == len(models), 'Number of models are not matched'
    for checkpoint, model in zip(cfg.TEST.RESTORE_FROM, models):
        print("准备加载模型",checkpoint)
        load_checkpoint_for_evaluation(model, checkpoint, device)
    # eval
    hist = np.zeros((cfg.NUM_CLASSES, cfg.NUM_CLASSES))
    for index, batch in tqdm(enumerate(test_loader)):
        # image, label, _, name = batch
        image, image2, _, _, name = batch
        file_name = name[0].split('/')[-1]
        print("文件名字",file_name)
        frame = int(file_name.replace('.png', ''))
        print("frame",frame)
        frame1 = frame - 1
        
        # flow_int16_x10_name = file_name.replace('leftImg8bit.png', str(frame1).zfill(6) + '_int16_x10')
        # flow_int16_x10 = np.load(os.path.join(cfg.TEST.flow_path, flow_int16_x10_name + '.npy'))
        
        flow_image_path = os.path.join(cfg.TEST.flow_path,"flow_map_"+str(frame1)+".png")
        print("光流图像路径",flow_image_path)
        flow_image = Image.open(flow_image_path).convert('RGB')  # 使用 PIL 库读取图片
        flow = transforms.ToTensor()(flow_image).unsqueeze(0)
        # print("光流",flow)
        # flow = torch.from_numpy(flow_int16_x10 / 10.0).permute(2, 0, 1).unsqueeze(0)
        
        npimage=image.detach().cpu().numpy()
        interp = nn.Upsample(size=(npimage.shape[0], npimage.shape[1]), mode='bilinear', align_corners=True)
        # if not fixed_test_size:
        #     interp = nn.Upsample(size=(label.shape[1], label.shape[2]), mode='bilinear', align_corners=True)
        with torch.no_grad():
            output = None
            for model, model_weight in zip(models, cfg.TEST.MODEL_WEIGHT):
                # print("设备",device)
                pred_main = models[0](image.cuda(device), image2.cuda(device), flow, device)[1]
                print("预测结果",pred_main)
                # for res in pred_main:
                #     print(res):
                output_ = interp(pred_main).cpu().data[0].numpy()
                if output is None:
                    output = model_weight * output_
                else:
                    output += model_weight * output_
            assert output is not None, 'Output is None'
            output = output.transpose(1, 2, 0)
            output = np.argmax(output, axis=2)
            amax_output_col = colorize_mask(np.asarray(output, dtype=np.uint8))
            name = name[0].split('/')[-1]
            image_name = name.split('.')[0]
            # vis seg maps
            os.makedirs(cfg.TEST.SNAPSHOT_DIR[0] + '/best_results', exist_ok=True)
            print("保存路径",'%s/%s_color.png' % (cfg.TEST.SNAPSHOT_DIR[0] + '/best_results', image_name))
            amax_output_col.save('%s/%s_color.png' % (cfg.TEST.SNAPSHOT_DIR[0] + '/best_results', image_name))

**config.py**：
import os.path as osp
import numpy as np
from easydict import EasyDict
from tps.utils import project_root, project_root_ADVENT
from advent.utils.serialization import yaml_load

cfg = EasyDict()

# COMMON CONFIGS (the same as Advent)
cfg.NUM_WORKERS = 4
cfg.EXP_NAME = ''
cfg.EXP_ROOT = project_root / 'experiments'
cfg.EXP_ROOT_SNAPSHOT = osp.join(cfg.EXP_ROOT, 'snapshots')
cfg.EXP_ROOT_LOGS = osp.join(cfg.EXP_ROOT, 'logs')
cfg.GPU_ID = 0
cfg.TENSORBOARD_DIR = ''
cfg.TRAIN = EasyDict()
cfg.TRAIN.SET_SOURCE = 'all'
cfg.TRAIN.SET_TARGET = 'train'
cfg.TRAIN.BATCH_SIZE_SOURCE = 1
cfg.TRAIN.BATCH_SIZE_TARGET = 1
cfg.TRAIN.IGNORE_LABEL = 255
cfg.TRAIN.INPUT_SIZE_SOURCE = [1280, 720]
cfg.TRAIN.INPUT_SIZE_TARGET = (1024, 512)
cfg.TRAIN.INFO_SOURCE = ''
cfg.TRAIN.MULTI_LEVEL = True
cfg.TRAIN.RESTORE_FROM = str(project_root / 'pretrained_models/DeepLab_resnet_pretrained_imagenet.pth')
cfg.TRAIN.IMG_MEAN = np.array((104.00698793, 116.66876762, 122.67891434), dtype=np.float32)
cfg.TRAIN.LEARNING_RATE = 2.5e-4
cfg.TRAIN.MOMENTUM = 0.9
cfg.TRAIN.WEIGHT_DECAY = 0.0005
cfg.TRAIN.POWER = 0.9
cfg.TRAIN.LAMBDA_SEG_MAIN = 1.0
cfg.TRAIN.LAMBDA_SEG_AUX = 0.1
cfg.TRAIN.MAX_ITERS = 250000
cfg.TRAIN.EARLY_STOP = 120000
cfg.TRAIN.SAVE_PRED_EVERY = 100
cfg.TRAIN.SNAPSHOT_DIR = '../../experiments/snapshots/tps_syn2city'
cfg.TRAIN.RANDOM_SEED = 1234
cfg.TRAIN.TENSORBOARD_LOGDIR = ''
cfg.TRAIN.TENSORBOARD_VIZRATE = 100
cfg.TRAIN.LAMBDA_T = 1.0

# TPS

cfg.TRAIN.DA_METHOD = 'TPS'
cfg.NUM_CLASSES = 15
cfg.SOURCE = 'Viper'
cfg.TARGET = 'CityscapesSeq'
cfg.TRAIN.INFO_TARGET = str(project_root / 'tps/dataset/CityscapesSeq_list/info_Viper.json')
cfg.DATA_LIST_SOURCE = str(project_root / 'tps/dataset/Viper_list/{}.txt')
cfg.DATA_LIST_TARGET = str(project_root / '{}.txt')
cfg.DATA_DIRECTORY_SOURCE = str(project_root / 'data/Viper')
cfg.DATA_DIRECTORY_TARGET = str(project_root / 'frame')
cfg.TRAIN.MODEL = 'ACCEL_DeepLabv2'
cfg.TRAIN.flow_path_src = '../../data/estimated_optical_flow_viper_train'
cfg.TRAIN.flow_path = '../../data/estimated_optical_flow_cityscapes_seq_train'
cfg.TRAIN.INTERVAL = 1
cfg.TRAIN.THRESHOLD = 0.0
cfg.TRAIN.SCALING_RATIO = [0.8, 1.2]

# TEST CONFIGS
cfg.TEST = EasyDict()
cfg.TEST.MODE = 'video_best'  # {'single', 'best'}
cfg.TEST.MODEL = ('ACCEL_DeepLabv2',)
cfg.TEST.MODEL_WEIGHT = (1.0,)
cfg.TEST.MULTI_LEVEL = (True,)
cfg.TEST.IMG_MEAN = np.array((104.00698793, 116.66876762, 122.67891434), dtype=np.float32)
cfg.TEST.RESTORE_FROM = ('/home/jyw/TPS/tps_syn2city_pretrained.pth',)
cfg.TEST.SNAPSHOT_DIR = ['../../experiments/snapshots/tps_syn2city']# used in 'best' mode
cfg.TEST.SNAPSHOT_STEP = 200  # used in 'best' mode
cfg.TEST.SNAPSHOT_START_ITER = 200  # used in 'best' mode
cfg.TEST.SNAPSHOT_MAXITER = 120000  # used in 'best' mode
cfg.TEST.SET_TARGET = 'val'
cfg.TEST.BATCH_SIZE_TARGET = 1
cfg.TEST.INPUT_SIZE_TARGET = (1024, 512)
cfg.TEST.OUTPUT_SIZE_TARGET = (2048, 1024)
cfg.TEST.INFO_TARGET = str(project_root / 'tps/dataset/cityscapes_list/info.json')
cfg.TEST.WAIT_MODEL = True
cfg.TEST.INTERVAL = 1
cfg.TEST.flow_path = '/home/jyw/TPS/save_flow'

def _merge_a_into_b(a, b):
    """Merge config dictionary a into config dictionary b, clobbering the
    options in b whenever they are also specified in a.
    """
    if type(a) is not EasyDict:
        return

    for k, v in a.items():
        # a must specify keys that are in b
        # if not b.has_key(k):
        if k not in b:
            raise KeyError(f'{k} is not a valid config key')

        # the types must match, too
        old_type = type(b[k])
        if old_type is not type(v):
            if isinstance(b[k], np.ndarray):
                v = np.array(v, dtype=b[k].dtype)
            else:
                raise ValueError(f'Type mismatch ({type(b[k])} vs. {type(v)}) '
                                 f'for config key: {k}')

        # recursively merge dicts
        if type(v) is EasyDict:
            try:
                _merge_a_into_b(a[k], b[k])
            except Exception:
                print(f'Error under config key: {k}')
                raise
        else:
            b[k] = v


def cfg_from_file(filename):
    """Load a config file and merge it into the default options.
    """
    yaml_cfg = EasyDict(yaml_load(filename))
    _merge_a_into_b(yaml_cfg, cfg)

**Comment by jiyuwangbupt** [comment]
Thank you very much. The environment is set up, but the final visualization result is in grayscale. I modified test.py, CityscapesSeq.py, base_dataset.py, config.py, and the eval_video_demo function.`
[Uploading tpscode.zip…]()
`

**Comment by jiyuwangbupt** [comment]
> Hi @jiyuwangbupt
> 
> Can you check if this may help you? ([NVIDIA/flownet2-pytorch#227](https://github.com/NVIDIA/flownet2-pytorch/issues/227))

Thank you very much. The environment is set up, but the final visualization result is in grayscale. I modified test.py, CityscapesSeq.py, base_dataset.py, config.py, and the eval_video_demo function.
[tpscode.zip](https://github.com/user-attachments/files/17796918/tpscode.zip)

**Comment by jiyuwangbupt** [comment]
![image](https://github.com/user-attachments/assets/59a922bc-8eff-4633-8f4b-c146129fabbb)

**Comment by xing0047** [comment]
Thanks for your feedback.

May I check pixel values for this figure?
