### ISSUE TITLE
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered

### ISSUE THREAD

**Issue by ZHE-SAPI** [xing0047/TPS#7]
I really enjoy reading your work！！
 At the same time, I encountered a problem in the operation of 
CUDA_ VISIBLE_ DEVICES=0 python train.py --cfg configs/tps_ viper2city.yml

Have you ever encountered such a problem? 
Could you please kindly tell me how to solve this problem? Thank you!
@xing0047 @Dayan-Guan 
---------------------
Error :
Traceback (most recent call last):
  File "./tps/scripts/train.py", line 160, in <module>
    main()
  File "./tps/scripts/train.py", line 157, in main
    train_domain_adaptation(model, source_loader, target_loader, cfg)
  File "/home/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/domain_adaptation/train_video_UDA.py", line 30, in train_domain_adaptation
    train_TPS(model, source_loader, target_loader, cfg)
  File "/home/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/domain_adaptation/train_video_UDA.py", line 179, in train_TPS
    src_pred_aux, src_pred, src_pred_cf_aux, src_pred_cf, src_pred_kf_aux, src_pred_kf = model(src_img_cf.cuda(device), src_img_kf.cuda(device), src_flow, device)
  File "/opt/software/anaconda3/envs/TPS/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/customer/Desktop/ZZ/FMFSemi/TransferLearning/examples/domain_adaptation/video_seg/TPS/tps/model/accel_deeplabv2.py", line 153, in forward
    pred_aux = self.sf_layer(torch.cat((cf_aux, self.warp_bilinear(kf_aux, flow_cf)), dim=1))
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCGeneral.cpp:371

**Comment by ZHE-SAPI** [comment]
Some categories in the ground trunk exceed --->
Warp does not work ---
Just set  _os.environ["CUDA_VISIBLE_DEVICES"] = '2'_  that will do
